# shellcheck shell=bash

# WSL Plus only changes interactive shells.
[[ $- == *i* ]] || return 0
[[ ${WSL_PLUS_DISABLE:-0} != 1 ]] || return 0

_wsl_plus_root=${WSL_PLUS_ROOT:-$HOME/.local/share/wsl-plus/current}
_wsl_plus_runtime=${WSL_PLUS_RUNTIME:-$HOME/.config/wsl-plus/runtime.conf}

[[ -r $_wsl_plus_runtime ]] || return 0

# Runtime configuration is generated by WSL Plus from validated key/value files.
# shellcheck disable=SC1090
. "$_wsl_plus_runtime"

if [[ ${WSL_PLUS_SCHEMA_VERSION:-1} == 1 ]]; then
  if [[ ${WSL_PLUS_POLICY:-} == home && ${WSL_PLUS_ENABLE_HOME_SESSIONS:-0} == 1 ]]; then
    WSL_PLUS_ENABLE_LOCAL_SESSIONS=1
    WSL_PLUS_SESSION_BACKEND=auto
  else
    WSL_PLUS_ENABLE_LOCAL_SESSIONS=0
    # shellcheck disable=SC2034 # Read by the session command through runtime compatibility.
    WSL_PLUS_SESSION_BACKEND=native
  fi
fi

wsl-plus() {
  "$WSL_PLUS_ROOT/bin/wsl-plus" "$@"
}

if [[ ${WSL_PLUS_ENABLE_HISTORY_SETTINGS:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/history.bash"
fi

if [[ ${WSL_PLUS_ENABLE_NAVIGATION_HELPERS:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/navigation.bash"
fi

if [[ ${WSL_PLUS_ENABLE_BLESH:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/blesh.bash"
fi

if [[ ${WSL_PLUS_ENABLE_FZF:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/fzf.bash"
fi

if [[ ${WSL_PLUS_ENABLE_ZOXIDE:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/zoxide.bash"
fi

if [[ ${WSL_PLUS_ENABLE_LOCAL_SESSIONS:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/sessions.bash"
fi

if [[ ${WSL_PLUS_ALLOW_WINDOWS_INTEROP:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/windows-interop.bash"
fi

if [[ ${WSL_PLUS_ALLOW_SHARED_SSH_AGENT:-0} == 1 \
  && ${WSL_PLUS_ALLOW_WINDOWS_INTEROP:-0} == 1 \
  && ${WSL_PLUS_ALLOW_CROSS_FILESYSTEM:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/ssh-agent.bash"
fi

if [[ ${WSL_PLUS_MANAGE_PROMPT:-0} == 1 ]]; then
  # shellcheck disable=SC1091
  . "$_wsl_plus_root/core/bash/prompt.bash"
fi

unset _wsl_plus_root _wsl_plus_runtime
